Repository wecode-bootcamp-korea/45-2nd-headbanger-Frontend, pull requests merged in 2023-05, with the labels that each got.

#2 [45기 이소진]Add : Footer 레이아웃 구현
  src/components/Footer/Footer.jsx
  src/components/Footer/Footertop.jsx
  src/styles/mixin.js
  src/styles/theme.js
Labels: 완료

#1 [45기 김준섭] Add: signup/login 페이지 레이아웃 구현
  public/data/data.json
  src/assets/images/Login/goback.png
  src/assets/images/Login/sample.png
  src/pages/Login/Login.jsx
  src/pages/Login/components/EmailVerification.jsx
  src/pages/Login/components/LoginForm.jsx
  src/pages/Login/components/SignupForm.jsx
  src/pages/Login/components/emailValidation.json
  src/pages/Signup/Signup.jsx
  src/styles/mixin.js
Labels: 수정 요청

#4 [45기 김태원] Add: mypage-layout 완료
  public/data/BookingData.json
  public/data/LogData.json
  public/data/WishList.json
  public/images/Mypage/campicon.png
  public/images/Mypage/couponicon.png
  public/images/Mypage/eventicon.png
  public/images/Mypage/fullstar.png
  public/images/Mypage/sample.png
  public/images/Mypage/star.png
  public/images/Mypage/tent.png
  src/assets/images/Mypage/BackgroundTheme/1.jpg
  src/assets/images/Mypage/BackgroundTheme/2.jpg
  src/assets/images/Mypage/BackgroundTheme/3.jpg
  src/assets/images/Mypage/BackgroundTheme/4.jpg
  src/assets/images/Mypage/BackgroundTheme/5.jpg
  src/assets/images/Mypage/BackgroundTheme/7.jpg
  src/assets/images/Mypage/sample.png
  src/pages/Mypage/MyCamping/MyCamping.jsx
  src/pages/Mypage/MyCamping/components/BookingList/BookingList.jsx
  src/pages/Mypage/MyCamping/components/BookingLog/BookingLog.jsx
  src/pages/Mypage/MyCamping/components/BookingLog/Review/Review.jsx
  src/pages/Mypage/MyCamping/components/CancleBooking/CancleBooking.jsx
  src/pages/Mypage/MyCamping/components/WishList/WishList.jsx
  src/pages/Mypage/MyPoint/MyPoint.jsx
  src/pages/Mypage/Mypage.jsx
  src/pages/Mypage/UserSetting/SettingModal/SettingModal.jsx
  src/pages/Mypage/UserSetting/UserSetting.jsx
Labels: 멘토 리뷰 요청

#6 [45기 김준섭] Add : redux 기능구현
  src/actions.js
  src/index.js
  src/reducer.js
Labels: 멘토 리뷰 요청

#8 [45김태원] Add: payment layout 완성
  public/images/Payment/pay-arrow-yellow.png
  public/images/Payment/pay-arrow.png
  public/images/Payment/pay-card.png
  public/images/Payment/pay-kakao.png
  public/images/Payment/pay-naver.png
  public/images/Payment/pay-toss.png
  public/images/Payment/right-arrow.png
  public/images/Payment/sample.png
  src/pages/Payment/Payment.jsx
  src/pages/Payment/componenets/Pay/Pay.jsx
  src/pages/Payment/componenets/PayFlow/PayFlow.jsx
Labels: 멘토 리뷰 요청

#10 [45기 김준섭]Modify : package.json 파일에 적절히 추가
  package-lock.json
  package.json
Labels: 멘토 리뷰 요청

#12 [45기 김준섭]Add : 자리 선택을 위한 redux 데이터 업데이트
  src/actions.js
  src/reducer.js
Labels: 멘토 리뷰 요청

#5 [45기 이수빈] Feature/productlist layout/function
  package-lock.json
  package.json
  public/data/campData.json
  public/images/Map/tent.png
  public/images/ProductsList/search.png
  public/index.html
  src/Router.js
  src/components/Nav/Nav.jsx
  src/components/Nav/SearchBar.jsx
  src/index.js
  src/pages/ProductsList/ProductsList.jsx
  src/pages/ProductsList/components/FilterBox.jsx
  src/pages/ProductsList/components/FilterDetail.jsx
  src/pages/ProductsList/components/ImagesContainer.jsx
  src/pages/ProductsList/components/KakaoMap.jsx
  src/pages/ProductsList/components/KakaoModal.jsx
  src/pages/ProductsList/components/OptionChecked.jsx
  src/pages/ProductsList/components/SearchInput.jsx
  src/pages/ProductsList/components/SortByBox.jsx
  src/styles/mixin.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#13 [45기 김태원] Add: mypage review tab 기능 구현
  src/pages/Mypage/MyCamping/MyCamping.jsx
  src/pages/Mypage/MyCamping/components/WishList/WishList.jsx
  src/pages/Mypage/MyPoint/MyPoint.jsx
  src/pages/Mypage/Mypage.jsx
Labels: 완료

#3 [45기 이수빈] Feature/login function
  .gitignore
  package-lock.json
  public/images/Login/kakao_login_large_wide.png
  public/images/Login/logo.png
  public/images/ProductsList/dylan-sauerwein-ot8_8qJZYcw-unsplash.jpg
  src/Router.js
  src/pages/Login/Login.jsx
  src/pages/Login/components/Auth.jsx
  src/pages/Login/components/EmailVerification.jsx
  src/pages/Login/components/KakaoSocialLogin.jsx
  src/pages/Login/components/LoginData.jsx
  src/pages/Login/components/LoginForm.jsx
  src/pages/Login/components/SignupForm.jsx
  src/pages/Login/components/emailValidation.json
  src/pages/Signup/Signup.jsx
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#17 [45기 이수빈] Add: header 레이아웃
  public/images/components/Header/userIcon.svg
  src/Router.js
  src/components/Header/Header.jsx
  src/pages/ProductsList/components/SearchInput.jsx
Labels: 멘토 리뷰 요청

#16 [45기 김태원] Add: 별점 및 리뷰 작성 기능 구현
  package-lock.json
  package.json
  public/images/Mypage/tent-modal.png
  src/Router.js
  src/pages/Mypage/MyCamping/components/BookingLog/BookingLog.jsx
  src/pages/Mypage/MyCamping/components/BookingLog/Review/Review.jsx
  src/pages/Mypage/MyCamping/components/BookingLog/Review/ReviewModal.jsx
  src/pages/Mypage/MyCamping/components/BookingLog/Review/StarRating.jsx
  src/pages/Mypage/MyCamping/components/BookingLog/Review/SuccessModal.jsx
  src/styles/theme.js
Labels: 완료

#15 [45기 이수빈] Productlist function 기능 구현
  .gitignore
  package-lock.json
  package.json
  public/images/Login/cvgLogo.svg
  public/images/Login/kakao_login_large_wide.png
  public/images/Login/naverBtn.svg
  public/images/Map/map.png
  public/images/Map/mapEntry.svg
  public/images/Map/mapImg.png
  public/images/ProductsList/emptyHeart.png
  public/images/ProductsList/heartImg.png
  public/images/ProductsList/tentIcon.png
  public/index.html
  src/Router.js
  src/actions.js
  src/components/Header/Header.jsx
  src/components/Nav/SearchBar.jsx
  src/config.js
  src/pages/Login/Login.jsx
  src/pages/Login/components/Auth.jsx
  src/pages/Login/components/KakaoSocialLogin.jsx
  src/pages/ProductsList/ProductsList.jsx
  src/pages/ProductsList/components/FilterDetail.jsx
  src/pages/ProductsList/components/HeartIcon.jsx
  src/pages/ProductsList/components/ImagesContainer.jsx
  src/pages/ProductsList/components/KakaoMap.jsx
  src/pages/ProductsList/components/KakaoModal.jsx
  src/pages/ProductsList/components/OptionChecked.jsx
  src/pages/ProductsList/components/SearchCamp.jsx
  src/pages/ProductsList/components/SiteBanner.jsx
  src/pages/ProductsList/components/SortByBox.jsx
  src/reducer.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청
